#!/bin/sh

mkdir -p ipkg/home/retrofw/games/blockout
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/games
cp ./blockout ipkg/home/retrofw/games/blockout/blockout
cp ./block_icon.png ipkg/home/retrofw/games/blockout/blockout.png
cp ../LICENSE.md ipkg/home/retrofw/games/blockout/COPYRIGHT
cp -r ./images ipkg/home/retrofw/games/blockout
cp -r ./sounds ipkg/home/retrofw/games/sounds

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: BlockOut
Version: 1.0
Description: Puzzle game
Section: games
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/blockout
Depends:
Source: https://github.com/gameblabla/blockout' > control

print '2.0' > debian-binary

print 'title=BlockOut
description=Puzzle game
exec=/home/retrofw/games/blockout/blockout
clock=600' > home/retrofw/apps/gmenu2x/sections/games/blockout

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../blockout.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
